# This is for the "pre-commit" tool, which enforces checks before local commits are allowed.
# <https://pre-commit.com/>

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:

  # Trims trailing whitespace.
  - id: trailing-whitespace

  # Prevent giant files from being committed.
  - id: check-added-large-files

  # Simply check whether files parse as valid python.
  - id: check-ast

  # Check for files that contain merge conflict strings.
  - id: check-merge-conflict

  # Attempts to load all xml files to verify syntax.
  - id: check-xml

  # Attempts to load all yaml files to verify syntax.
  - id: check-yaml

  # Check for debugger imports and py37+ breakpoint() calls in python source.
  - id: debug-statements

  # Makes sure files end in a newline and only a newline.
  - id: end-of-file-fixer

  # Sorts entries in requirements.txt and removes incorrect entry for pkg-resources==0.0.0
  - id: requirements-txt-fixer

  # Replaces or checks mixed line ending.
  - id: mixed-line-ending
    args: [--fix=no]

# Format YAML files.
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

# Remove spurious flake8 noqa (ignore) comments.
- repo: https://github.com/asottile/yesqa
  rev: v1.4.0
  hooks:
  - id: yesqa

# Organize imports.
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
    args: [--settings-path=pyproject.toml]

# Automatically format code.
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    language_version: python3

# Upgrade code style to the current Python version.
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args: [--py310-plus, --keep-runtime-typing]

# BELOW: ENFORCE CODING CONVENTIONS
# Warning: some of these can be quite strict.

# Enforce style.
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8

# Type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    args: [--install-types, --non-interactive]
