# This is for the "pre-commit" tool, which enforces checks before local commits are allowed.
# <https://pre-commit.com/>

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:

  # Trims trailing whitespace.
  - id: trailing-whitespace

  # Prevent giant files from being committed.
  - id: check-added-large-files

  # Simply check whether files parse as valid python.
  - id: check-ast

  # Check for files that contain merge conflict strings.
  - id: check-merge-conflict

  # Attempts to load all xml files to verify syntax.
  - id: check-xml

  # Attempts to load all yaml files to verify syntax.
  - id: check-yaml

  # Check for debugger imports and py37+ breakpoint() calls in python source.
  - id: debug-statements

  # Makes sure files end in a newline and only a newline.
  - id: end-of-file-fixer

  # Sorts entries in requirements.txt and removes incorrect entry for pkg-resources==0.0.0
  - id: requirements-txt-fixer

  # Replaces or checks mixed line ending.
  - id: mixed-line-ending
    args: ['--fix=no']

# Upgrade code style to the current Python version.
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: ["--py310-plus", "--keep-runtime-typing"]

# Organize imports.
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.6.4
  hooks:
  - id: isort
    args: ["--profile", "black"]

# Automatically format code.
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3

# Enforce coding conventions. WARNING: this is quite strict.
- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ['--max-line-length=88']  # default of Black
