version: "3.8"

services:
    # This name needs to agree with the value of "service" in devcontainer.json.
    example-project-dev:
        build:
            context: ../
            dockerfile: .devcontainer/dev.Dockerfile

        hostname: example-project-hostname

        # Start as root and then step down to mambauser.
        user: root

        # ports:
        #     - "127.0.0.1:8000:8000"

        volumes:
            # Mount the local source directory.
            - ${HOST_SOURCE_DIR}:/work
            # Prevent VS Code from needing to redownload extensions each time.
            - vscode-storage:/mnt/.vscode-server
            # Allow for Docker access within the container.
            - /var/run/docker.sock:/var/run/docker.sock

        # Share the environment variables with the container
        env_file:
            - .env

        # Overrides default command so things don't shut down after the process ends.
        command: /bin/bash -c "echo running docker-compose command to sleep; while sleep 1000; do :; done"

volumes:
  vscode-storage:
