name: base
channels:
  - conda-forge

  # The following are necessary to install the dev version of Poetry. See
  # <https://github.com/conda-forge/poetry-feedstock/issues/57#issuecomment-1022805023>
  - conda-forge/label/poetry_dev
  - conda-forge/label/cleo_dev

dependencies:
  - python =3.10
  - git  # Also installed from Ubuntu, but this is newer.
  - xonsh
  - poetry >=1.2.0a2
  - poetry-core ==1.1.0a7  # The solver seems broken in the 1.1.0b# series.
  - pre-commit
  - black
  - isort
  - flake8
  - pytest
  - pytest-asyncio
  - mamba
  - pipx
  - condax
  - conda-lock
  - ipykernel  # Jupyter notebooks in VS Code
  - nbformat  # Additional utilities for Jupyter notebooks (e.g. Plotly support)
  - line_profiler
  - cookiecutter
  - cruft
  - flake8-use-fstring
  - flake8-blind-except
  - flake8-builtins
  - flake8-use-pathlib
  - flake8-noqa
  - pip

  # # In case you want to install packages from PyPI which aren't on Conda-Forge,
  # # uncomment this block and add them as follows:
  # - pip:
  #   - flake8-noqa  # Example
