name: base
channels:
  - conda-forge

  # The following are necessary to install the dev version of Poetry. See
  # <https://github.com/conda-forge/poetry-feedstock/issues/57#issuecomment-1022805023>
  - conda-forge/label/poetry_dev
  - conda-forge/label/cleo_dev

dependencies:
  - python =3.10
  - git  # Also installed from Ubuntu, but this is newer.
  - xonsh
  - poetry >=1.2.0a2
  - pre-commit
  - black
  - isort
  - flake8
  - pytest
  - pytest-asyncio
  - mamba
  - pipx
  - condax
  - conda-lock
  - ipykernel
  - line_profiler
  - cookiecutter
  - flake8-use-fstring
  - flake8-blind-except
  - flake8-builtins
  - flake8-use-pathlib
  - pip
  - pip:
    - flake8-noqa
